# ── World ─────────────────────────────────────────────────────────────────────
[world]
bounds_radius            = 60000.0
max_protozoa             = 100000
initial_protozoa         = 10000
border_repulsion_magnitude = 0.001
max_speed                = 30.0
cells_x = 200
cells_y = 200
cell_max_capacity = 25

# ── Protozoa ──────────────────────────────────────────────────────────────────
[protozoa]
max_cells                = 15
spawn_radius             = 100.0
energy_decay_rate        = 0.15
wander_threshold         = 600.0   
breaking_length          = 540.0   
maximum_extension        = 360.0    
spring_work_const        = 0.00001
reproductive_cooldown    = 200
digestive_time           = 100
initial_energy           = 300.0


# ── Food ──────────────────────────────────────────────────────────────────────
[food]
max_food = 100000
initial_food = 70000

# --- spatial grid ---
cells_x = 200
cells_y = 200
cell_max_capacity        = 25
update_freq = 4

# --- physics ---
food_radius              = 30.0
friction                 = 0.915
vibration_strength       = 3.0

# --- Color ---
food_visibility_ramp_frames = 90.0
food_max_alpha           = 200.0

# --- Birth ---
spawn_proportionality_constant = 0.045
food_spawn_distance      = 200.0 
reproductive_cooldown    = 220
reproductive_threshold   = 300

# --- Nutrients ---
initial_nutrients        = 5.0
final_nutrients          = 60.0
nutrient_development_time = 400

# --- Death ---
death_age                = 700.0
death_age_chance         = 0.01

# ── Graphics ──────────────────────────────────────────────────────────────────
[graphical]
spring_thickness         = 9.0
spring_outline_thickness = 6.0
cell_outline_thickness   = 1.1
food_transparency        = 200

# ── Simulation ────────────────────────────────────────────────────────────────
[simulation]
vsync                    = false
full_screen              = false
ui_scale_percent         = 100.0
max_fps                  = 0
